# Generated by Django 5.2.7 on 2025-11-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='precio_dia',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='core.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='estado',
            field=models.CharField(choices=[('available', 'Disponible'), ('rented', 'Alquilado')], default='available', max_length=20),
        ),
    ]
